repos:
  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.2.0
    hooks:
      - id: conventional-gitmoji
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
